BaseUrl= "http://example.com/"
LanguageCode= "zh-CN"
Title= "USTC-CS Student Union"
paginate = 5
DisqusShortname = "USTC-CS"
Copyright = "All rights reserved - 2021"
canonifyurls = true

[params]
  description = "USTC-CS Student Union"
  cover = "images/cover.jpg"
  author = "USTC-CS"
  authorlocation = "Hefei, Anhui"
  bio= "my bio"
  logo = "images/logo.png"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "USTC-CS"
  #twitterName = "vjeantet"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true